apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-igrow
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: java
  template:
    metadata:
      labels:
        component: java
    spec:
      containers:
        - image: horatiut98/igrow-backend
          name: server
          ports:
            - containerPort: 8080
