apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-igrow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - image: horatiut98/graphql-frontend-proxy-service-name	
        name: client
        ports: 
          - containerPort: 3000