apiVersion: v1
kind: Service
metadata:
  name: igrow-frontend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    component: web
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000


